# Generated by Django 3.0.7 on 2020-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeatIngridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_ingredient', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherIngridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_ingredient', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VegetablesIngridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetables_ingredient', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
